fixtures:
  repositories:
    java:
      repo: 'https://github.com/puppetlabs/puppetlabs-java.git'
      ref: '1.6.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.6.0'
    wget:
      repo: 'https://github.com/maestrodev/puppet-wget.git'
      ref: 'v1.2.2'
    logrotate:
      repo: 'https://github.com/voxpupuli/puppet-logrotate.git'
      ref:  'v3.3.0'
  symlinks:
    selenium: "#{source_dir}"
